### ISSUE TITLE
DB.py dies with error

### ISSUE THREAD

**Issue by jidicula** [Adoria/Martlet#19]
When %q is called with a username that doesn't exist, the bot exits. Might need something to ignore the exception.

`Ignoring exception in command q
Traceback (most recent call last):
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 362, in invoke
    yield from self.prepare(ctx)
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 340, in prepare
    yield from self._parse_arguments(ctx)
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 299, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 218, in transform
    raise e
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 216, in transform
    return (yield from self.do_conversion(ctx, converter, argument))
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 179, in do_conversion
    return instance.convert()
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/converter.py", line 100, in convert
    raise BadArgument('Member "{}" not found'.format(self.argument))
discord.ext.commands.errors.BadArgument: Member "squad" not found`

**Comment by Adoria** [comment]
Does it actually exit or just throw the error? I get the same results, but the bot continues to run without a problem.

**Comment by jidicula** [comment]
just retested and it didn't exit.
